routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::group(['namespace' => 'admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function() {

	Route::get('/dashboard','DashboardController@index')->name('dashboard');

	/**
	* Admin Resources Module Routes
	*/
	Route::resources([
		'permissions'   => 'PermissionsController',
		'tasks'   => 'TasksController',
	]);

	Route::get('/timeline/{task_id}','TasksController@timeline')->name('tasks.timeline');
	Route::get('/tasklist/{cat_id}','TasksController@tasklist')->name('tasks.list');
	Route::get('/loadForm/{form_id}','TasksController@loadForm')->name('tasks.form');
	Route::post('/storeResponse','TasksController@storeResponse')->name('tasks.response');
});

Route::get('/pusher', function() {
    event(new App\Events\HelloPusherEvent('Hi there Pusher!'));
    return "Event has been sent!";
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    /**
     * Model Table
     */
    protected $table = 'tasks';

    /**
     * Primary key of table
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'task_no', 'category_id', 'status'
    ];

    /**
     * Guarded fileds which are prevented from mass-assignment
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        
    ];
}

app/Http/Controllers/admin/TasksController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth; 

use App\Http\Controllers\Controller;
use DB;

use App\Repositories\Admin\Task\TaskRepository;
use App\Repositories\Admin\Thread\ThreadRepository;
use App\Events\HelloPusherEvent;

class TasksController extends Controller
{
    /**
     * Task Repository instance
     */
    private $taskRepository;
    private $threadRepository;

    /**
     * Default Constructor
     */
    public function __construct(TaskRepository $taskRepository,ThreadRepository $threadRepository)
    {
        /**
         * Set Current Module Name
         */
        $this->moduleName = __('crud.sys_tasks');
        /**
         * Current Repository Instances
         */
        $this->taskRepository = $taskRepository;
        $this->threadRepository = $threadRepository;

        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['categories'] = DB::table('categories')
                ->select('categories.id','categories.name','categories.description',DB::raw('COUNT(DISTINCT tasks.id) AS task_cnt,MAX(tasks.id) AS task_id,MAX(tasks.task_no) AS task_no,MAX(threads.title) AS title,MAX(tasks.created_at) as created_at'))
                ->join('tasks', 'categories.id', '=', 'tasks.category_id')
                ->join('threads','threads.task_id', '=', 'tasks.id')->where('threads.id','>','tasks.id')
                ->where(function ($query) {
                    if(Auth::user()->id != 1) { //admin id : 1 
                        $query->where('threads.user_id',Auth::user()->id)
                        ->orWhereRaw('FIND_IN_SET(threads.assigned_to,'.Auth::user()->id.') <> 0');
                    }
                })
                ->groupBy('categories.id','categories.name','categories.description')->get();

        return view('admin.task.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['users']          = DB::table('users')->get();
        $data['categories']     = DB::table('categories')->get();
        $data['actionURL']      = route('admin.tasks.store');

        return view('admin.task.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $userID = Auth::user()->id;
        $input              = $request->all();
        $input['task_no']   = $this->generateRandomString().date('Y');

        $createTask     = $this->taskRepository->create($input);
        $task_id      = $createTask->getOriginal('id');
        
        $input['user_id']   = $userID; // for pusher
        $input['task_id'] = $task_id; // for pusher routing
        $assigned_to = $input['assigned_to'];
        $threadData = array(
            "task_id"       => $task_id,
            "thread_type"   => 1,
            "user_id"       => $userID,
            "title"         => $input['title'],
            "description"   => $input['description']
        );

        $createThread    = $this->threadRepository->create($threadData);
        if(!empty($assigned_to)) {
            $this->assignTask($assigned_to,$task_id,$userID);
        }
        if($createTask && $createThread) {
            event(new HelloPusherEvent($input));
            return redirect()->back()->with('successmsg', 'Task assigned successfully');
        } else {
            return redirect()->back()->with('errormsg', 'Failed to assign task');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Display task timeline
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function timeline(Request $request,$task_id)
    {
        $this->viewData['threads'] = DB::table('threads')
                            ->select('tasks.id','tasks.task_no','tasks.status','threads.title','threads.description','threads.thread_type','threads.user_id','threads.assigned_to',DB::raw('tasks.created_at as task_created_at, tasks.updated_at as task_updated_at, threads.created_at as thread_created_at'))
                            ->join('tasks','tasks.id','=','threads.task_id')
                            ->orderBy('threads.created_at','asc')
                            ->where('task_id',$task_id)->get();
        return view('admin.task.timeline')->with($this->viewData);
    }

    /**
     * Display task list based on category
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function tasklist(Request $request,$cat_id)
    {
        $this->viewData['tasks'] = DB::table('tasks')
                            ->join('threads','threads.task_id','=','tasks.id')
                            ->whereNotNull('threads.title')
                            ->where('category_id',$cat_id)->get();
        return view('admin.task.list')->with($this->viewData);
    }

    /**
     * Display task list based on category
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function assignTask($assigned_to,$task_id,$userID) 
    {
        $threadData = array(
            "task_id"       => $task_id,
            "thread_type"   => 2,
            "user_id"       => $userID,
            "assigned_to"   => $assigned_to,
            "description"   => "Task Assigned"
        );

        $assignTask = $this->threadRepository->create($threadData);
        return $assignTask;
    }

    /**
     * Display task list based on category
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function loadForm(Request $request,$form_id)
    {
        $input = $request->all(); //for task_id
        $this->data['task_id'] = $input['task_id'];

        $this->page                 = "admin.task.form";
        $this->data['form_id']      = $form_id;
        $this->data['users']        = DB::table('users')->get();
        $this->data['actionURL']    = route('admin.tasks.response');
        if ($request->ajax()) {
            $html = view($this->page)->with($this->data)->render();
            return response()->json( array('status' => true, 'page'=>$html) );
        } 
    }

    /**
     * Display task list based on category
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function storeResponse(Request $request)
    {
        $input      = $request->all();
        $input['user_id'] = Auth::user()->id;
        $responseType = $input['response_type'];
        $task_id = $input['task_id'];

        if($responseType == 1) { //reassign task
            $input['thread_type'] = 4;
            $response   = $this->threadRepository->create($input);
        } else if($responseType == 2) { //add comment
                $input['thread_type'] = 3;
                $response   = $this->threadRepository->create($input);
        } else if($responseType == 3) { //mark as done
            $updateData = array(
                'status' => 1
            );
            $response = $this->taskRepository->update($updateData, $task_id);
        } else if($responseType == 4) { //redo task
            $updateData = array(
                'status' => 2
            );
            $response = $this->taskRepository->update($updateData, $task_id);
        }

        if($response) {
            return response()->json( array('status' => true, 'message' => 'Success') );
        }else {
            return response()->json( array('status' => false, 'message' => 'Error') );
        }
    }

    public function generateRandomString($length = 10) {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }

    public static function getusername($id)
    {
        $user = DB::table('users')
            ->where('id',$id)->get()->first()->name;

        return $user;
    }

    public static function gettitle($id)
    {
        $title = DB::table('threads')
            ->where('task_id',$id)->whereNotNull('title')->get()->first()->title;

        return $title;
    }
}

resources/views/admin/task/create.blade.php
@extends('template.layout')

@section('content')
<style type="text/css">
	.help-block {
		color: red;
	}
</style>
<div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href="#">Home</a>
			</li>

			<li class="active">Tasks</li>
		</ul><!-- /.breadcrumb -->
	</div>
	<div class="page-content">
		<div class="page-header">
			<div class="row">
				<div class="col-xs-10">
					<h1>
						Add Task
						<small>
							<i class="ace-icon fa fa-angle-double-right"></i>
							Assign task 
						</small>
					</h1>
				</div>
			</div>
		</div><!-- /.page-header -->
		<!-- PAGE CONTENT BEGINS -->
		<div class="row">
			@if (Session::has('successmsg'))
				<div class="alert alert-block alert-success">
					<button type="button" class="close" data-dismiss="alert">
						<i class="ace-icon fa fa-times"></i>
					</button>

					<p>
						<strong>
							<i class="ace-icon fa fa-check"></i>
							Well done!
						</strong>
						{{ Session::get('successmsg') }}
					</p>
				</div>
			@endif
			<div class="col-xs-12">
				<div class="col-xs-12 col-sm-12">
					<div class="widget-box">
						<div class="widget-header">
							<h4 class="widget-title">Text Area</h4>

							<div class="widget-toolbar">
								<a href="#" data-action="collapse">
									<i class="ace-icon fa fa-chevron-up"></i>
								</a>

								<a href="#" data-action="close">
									<i class="ace-icon fa fa-times"></i>
								</a>
							</div>
						</div>

						<div class="widget-body">
							<div class="widget-main">
								<form action="{{ $actionURL }}" method="POST" id="task-form">
									@csrf
									<div class="row">
										<div class="col-sm-3">
											<label for="form-field-8">Task Category</label>

											<select class="form-control" id="form-field-8" name="category_id">
												<option value="">Select Category</option>
												@foreach($categories as $category)
													<option value="{{ $category->id }}">{{ $category->name }}</option>
												@endforeach
											</select>
										</div>

										<div class="col-sm-3">
											<label for="form-field-8">Task Title</label>

											<input class="form-control" id="form-field-8" placeholder="Task Title" name="title">
										</div>

										<div class="col-sm-3">
											<label for="form-field-8">Task Assigned to</label>

											<select class="form-control" id="form-field-8" name="assigned_to">
												<option value="">Select User</option>
												@foreach($users as $user)
													<option value="{{ $user->id }}">{{ $user->name }}</option>
												@endforeach
											</select>
										</div>
									</div>

									<hr>

									<div class="row">
										<div class="col-sm-3">
											<label for="form-field-8">Task Description</label>

											<textarea class="form-control" id="form-field-8" placeholder="Description" name="description"></textarea>
										</div>
									</div><br>

									<div class="row">
										<div class="col-sm-12">
											<input type="submit" class="btn btn-success" value="Add">
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div><!-- /.span -->
		</div><!-- /.row -->
		<!-- PAGE CONTENT ENDS -->
			
	</div>
</div>
@endsection

resources/views/admin/task/form.blade.php
<form action="{{ $actionURL }}" method="POST" id="responseform">
	@csrf
	<input type="hidden" name="task_id" value="{{ $task_id }}" readonly="">
	{{-- for response type --}}
	<input type="hidden" name="response_type" value="{{ Request::segment(3) }}" readonly="">
	@if($form_id == 1) {{--  Reassign Form --}}
		<div class="row">
			<div class="col-sm-8">
				<label for="form-field-8">Task Assigned to</label>

				<select class="form-control" id="form-field-8" name="assigned_to">
					<option value="">Select User</option>
					@foreach($users as $user)
						<option value="{{ $user->id }}">{{ $user->name }}</option>
					@endforeach
				</select>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-8">
				<label for="form-field-8">Description</label>

				<textarea class="form-control" id="form-field-8" placeholder="Description" name="description"></textarea>
			</div>
		</div>
		</div>
	@elseif($form_id == 2) {{-- Add response form --}}
		<div class="row">
			<div class="col-sm-8">
				<label for="form-field-8">Description</label>

				<textarea class="form-control" id="form-field-8" placeholder="Description" name="description"></textarea>
			</div>
		</div>
	@elseif($form_id == 3) 
		<div class="row">
			<div class="col-sm-12">
				<h4><div class='alert alert-danger'>You are going to mark the task as done !!</div></h4>
			</div>
		</div>
	@elseif($form_id == 4) 
		<div class="row">
			<div class="col-sm-12">
				<h4><div class='alert alert-danger'>You are going to mark this task as re-do !!</div></h4>
			</div>
		</div>
	@endif
</form>

resources/views/admin/task/index.blade.php
<?php use \App\Http\Controllers\admin\TasksController; ?>
@extends('template.layout')

@section('content')
<div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href="#">Home</a>
			</li>

			<li class="active">Tasks</li>
		</ul><!-- /.breadcrumb -->
	</div>
	<div class="page-content">

		<div class="page-header">
			<div class="row">
				<div class="col-xs-10">
					<h1>
						Tasks
						<small>
							<i class="ace-icon fa fa-angle-double-right"></i>
							List of assigned Tasks
						</small>
					</h1>
				</div>
				<div class="col-xs-2">
					<p class="pull-right">
						<a href="{{ route('admin.tasks.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Add Task</a>
					</p>
				</div>
			</div>
		</div><!-- /.page-header -->
		<!-- PAGE CONTENT BEGINS -->
		<div class="row">
			<div class="col-xs-12">
				<table id="simple-table" class="table  table-bordered table-hover">
					<thead>
						<tr>
							<td style="width: 150px !important">Category Title</td>
							<td>Last Task</td>
						</tr>
					</thead>
					<tbody>
						@foreach($categories as $category) 
							<tr>
								<td>
									<a href="{{ route('admin.tasks.list',$category->id) }}">
										{{ $category->name }} ({{ $category->task_cnt }})
									</a><br>
									<small>{{ $category->description }}</small>
								</td>
								<td>
									<a href="{{ route('admin.tasks.timeline',$category->task_id) }}">
										<b>{{ $category->task_no }}</b> : {{ !empty($category->title) ? $category->title : TasksController::gettitle($category->task_id) }}
									</a></p>
									<b>Created On: </b> {{ $category->created_at }}
								</td>
							</tr>
						@endforeach

						@if(empty($category))
							<tr>
								<td colspan="2">No records yet !!</td>
							</tr>
						@endif
					</tbody>
				</table>
			</div><!-- /.span -->
		</div><!-- /.row -->
		<!-- PAGE CONTENT ENDS -->
	</div>
</div>
@endsection

resources/views/admin/task/list.blade.php
@extends('template.layout')

@section('content')
<div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href="#">Home</a>
			</li>

			<li class="active">Tasks</li>
		</ul><!-- /.breadcrumb -->
	</div>
	<div class="page-content">

		<div class="page-header">
			<div class="row">
				<div class="col-xs-10">
					<h1>
						Tasks
						<small>
							<i class="ace-icon fa fa-angle-double-right"></i>
							List of assigned Tasks
						</small>
					</h1>
				</div>
			</div>
		</div><!-- /.page-header -->
		<!-- PAGE CONTENT BEGINS -->
		<div class="row">
			<div class="col-xs-12">
				<table id="simple-table" class="table  table-bordered table-hover">
					<thead>
						<tr>
							<th>S.N</th>
							<th>Task No.</th>
							<th>Title</th>
							<th>Description</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($tasks as $task)
							<tr>
								<td>{{ $loop->iteration }}</td>
								<td>{{ $task->task_no }}</td>
								<td>{{ $task->title }}</td>
								<td>{{ $task->description }}</td>
								<td>
									<a href="#" class="btn btn-sm btn-primary">
										<span class="fa fa-edit"></span>
									</a>
									<a href="#" class="btn btn-sm btn-danger">
										<span class="fa fa-trash"></span>
									</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div><!-- /.span -->
		</div><!-- /.row -->
		<!-- PAGE CONTENT ENDS -->
	</div>
</div>
@endsection

resources/views/admin/task/timeline.blade.php
<?php use \App\Http\Controllers\admin\TasksController; ?>
@extends('template.layout')
<?php //dd($threads); exit; ?>
@section('content')
	<div class="page-content">
		<div class="page-header">
			<h1>
				{{ $threads[0]->title }}
				<small>
					<i class="ace-icon fa fa-angle-double-right"></i>
					{{ $threads[0]->task_no }}
				</small>
			</h1>
		</div><!-- /.page-header -->

		<div id="timeline-1">
			<div class="row">
				<div class="col-xs-12 col-sm-10 col-sm-offset-1">
					<div class="timeline-container">
						@foreach($threads as $thread)
							<div class="timeline-label">
								<span class="label label-primary arrowed-in-right label-lg">
									<b>{{ (date("Y-m-d") == date('Y-m-d',strtotime($thread->thread_created_at))) ? 'Today' : date('Y-m-d',strtotime($thread->thread_created_at)) }}</b>
								</span>
							</div>

							<div class="timeline-items">
								<div class="timeline-item clearfix">
									<div class="timeline-info">
										<img alt="Susan't Avatar" src="{{ asset('assets/images/avatars/avatar1.png') }}">
										<span class="label label-info label-sm">{{ date('H:i:s',strtotime($thread->thread_created_at)) }}</span>
									</div>

									<div class="widget-box transparent">
										<div class="widget-header widget-header-small">
											<h5 class="widget-title smaller">
												<a href="#" class="blue">{{ TasksController::getusername($thread->user_id) }}</a>
												<span class="grey">
													@if($thread->thread_type == 1) 
														added a task
													@elseif($thread->thread_type == 2)
														assigned task to <a href="#" class="blue">{{ TasksController::getusername($thread->assigned_to) }}</a>
													@elseif($thread->thread_type == 3)
														added a comment
													@elseif($thread->thread_type == 4)
														re-assigned task to <a href="#" class="blue">{{ TasksController::getusername($thread->assigned_to) }}</a>
													@endif
												</span>
											</h5>

											<span class="widget-toolbar no-border">
												<i class="ace-icon fa fa-clock-o bigger-110"></i>
												{{ date('H:i:s',strtotime($thread->thread_created_at)) }}
											</span>

											<span class="widget-toolbar">
												<a href="#" data-action="reload">
													<i class="ace-icon fa fa-refresh"></i>
												</a>

												<a href="#" data-action="collapse">
													<i class="ace-icon fa fa-chevron-up"></i>
												</a>
											</span>
										</div>

										<div class="widget-body">
											<div class="widget-main">
												{{ $thread->description }}
												<div class="space-6"></div>
											</div>
										</div>
									</div>
								</div>
							</div><!-- /.timeline-items -->
						@endforeach

						@if($threads[0]->status == 1)
							<div class="timeline-label">
								<span class="label label-primary arrowed-in-right label-lg">
									<b>{{ (date("Y-m-d") == date('Y-m-d',strtotime($threads[0]->task_updated_at))) ? 'Today' : date('Y-m-d',strtotime($threads[0]->task_updated_at)) }}</b>
								</span>
							</div>

							<div class="timeline-item clearfix">
								<div class="timeline-info">
									<i class="timeline-indicator ace-icon fa fa-check btn btn-success no-hover"></i>
								</div>

								<div class="widget-box transparent">
									<div class="widget-body">
										<div class="widget-main">
											Task has been marked as completed
											<div class="pull-right">
												<i class="ace-icon fa fa-clock-o bigger-110"></i>
												{{ date('H:i:s',strtotime($threads[0]->task_updated_at)) }}
											</div>
										</div>
									</div>
								</div>
							</div>
						@endif

						@if($threads[0]->status == 2)
							<div class="timeline-label">
								<span class="label label-primary arrowed-in-right label-lg">
									<b>{{ (date("Y-m-d") == date('Y-m-d',strtotime($threads[0]->task_updated_at))) ? 'Today' : date('Y-m-d',strtotime($threads[0]->task_updated_at)) }}</b>
								</span>
							</div>

							<div class="timeline-item clearfix">
								<div class="timeline-info">
									<i class="timeline-indicator ace-icon fa fa-check btn btn-success no-hover"></i>
								</div>

								<div class="widget-box transparent">
									<div class="widget-body">
										<div class="widget-main">
											Task has been marked to re-do
											<div class="pull-right">
												<i class="ace-icon fa fa-clock-o bigger-110"></i>
												{{ date('H:i:s',strtotime($threads[0]->task_updated_at)) }}
											</div>
										</div>
									</div>
								</div>
							</div>
						@endif
					</div><!-- /.timeline-container -->

					@if($threads[0]->status != 1)
						<p class="pull-right">
							<a href="javascript:;" data-href="{{ route('admin.tasks.form',3) }}" class="btn btn-white btn-success btn-bold bootbox-regular" data-title="Are you sure ?" data-formid="#responseform" data-responsetype = '3'>
								<i class="ace-icon fa fa-check bigger-120 green"></i>
								Mark as Done
							</a>

							<a href="javascript:;" data-title="Re-assign task" data-href="{{ route('admin.tasks.form',1) }}" class="btn btn-white btn-danger btn-bold bootbox-regular" data-formid="#responseform" data-responsetype = '1'>
								<i class="ace-icon fa fa-retweet bigger-120 red"></i>
								Re-assign
							</a>

							<a href="javascript:;" data-title="Add Response" data-href="{{ route('admin.tasks.form',2) }}" class="btn btn-white btn-success btn-bold bootbox-regular" data-formid="#responseform">
								<i class="ace-icon fa fa-reply bigger-120 blue" data-responsetype = '2'></i>
								Add response
							</a>
						</p>
					@else
						<p class="pull-right">
							<a href="javascript:;" data-href="{{ route('admin.tasks.form',4) }}" class="btn btn-white btn-danger btn-bold bootbox-regular" data-title="Are you sure?" data-formid='#responseform' data-responsetype = '4'>
								<i class="ace-icon fa fa-refresh bigger-120 red"></i>
								Redo Task
							</a>
						</p>
					@endif
				</div>
			</div>
		</div>
	</div>
@endsection